<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4398c0a9-c80b-45df-bfb2-2c1f0c883328</UserSecretsId>
  </PropertyGroup>

 <ItemGroup>
    <None Include="wwwroot\*" />
 </ItemGroup>

 <ItemGroup>
   <Folder Include="Properties\PublishProfiles\" />
 </ItemGroup>

 <ItemGroup>
   <PackageReference Include="AWSSDK.S3" Version="4.0.102.2" />
 </ItemGroup>

 <ItemGroup>
   <ProjectReference Include="..\Shared\Shared.csproj" />
 </ItemGroup>

</Project>
